name: Deploy Epistemic Architecture
on:
  push:
    paths:
      - 'framework/arena/**'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - checkout: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './framework/arena/tesseract'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
